# Generated by Django 3.2.2 on 2023-06-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
                ('operation', models.CharField(choices=[('START', 'START'), ('STOP', 'STOP'), ('STATUS', 'STATUS')], default='STATUS', max_length=10)),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
