# Generated by Django 3.2.2 on 2023-06-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_command_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ['creation_date']},
        ),
        migrations.AlterField(
            model_name='command',
            name='operation',
            field=models.CharField(choices=[('start', 'start'), ('stop', 'stop'), ('status', 'status')], default='status', max_length=10),
        ),
        migrations.AlterField(
            model_name='command',
            name='service',
            field=models.CharField(choices=[('jupyter', 'jupyter'), ('nifi', 'nifi'), ('hadoop', 'hadoop'), ('spark', 'spark'), ('kafka', 'kafka'), ('mariadb', 'mariadb'), ('mysql', 'mysql'), ('superset', 'superset'), ('mongodb', 'mongodb'), ('minio', 'minio'), ('airflow', 'airflow'), ('truckfleet-sim', 'truckfleet-sim')], default='jupyter', max_length=20),
        ),
    ]
